### ISSUE TITLE
Documentation in README.md

### ISSUE THREAD

**Issue by davecash75** [UCL-MIRSG/xnat-aws#101]
### Short Description

Under step 3 of the README.md it states:
```
cp terraform.tfvars.example terraform.tfvars
```
However the `provision` folder of `xnat-aws`, the file appears to be called `terraform.tfvars_sample` instead

### Evidence/Steps to Reproduce

See README file

### Acceptance Criteria/Expected Behaviour

Change to the documentation

**Comment by davecash75** [comment]
Also @milanmlft you may want to put a prompt in for people that they need to put in the value true or false when prompted for AppStream. It wasn't clear from the instructions when I wrote `terraform apply`, so I wrote `yes` originally and got an error.

**Comment by davecash75** [comment]
I see that the correct name `terraform.tfvars_sample` and mention of using true for Appstream is in the Provision README, but you may want to put it also in the main README as people might not see that before they go headlong into the terraform process.  Also, we may want make people aware of if they click on AppStream, then they need to have an image accesible to them with the name in their terraform.tfvars. Otherwise it hangs.

**Comment by ruaridhg** [comment]
I'm going to update the docs with your comments @davecash75 and some of my own
