### ISSUE TITLE
Container service and XNAT compatible with Docker > 24

### ISSUE THREAD

**Issue by davecash75** [UCL-MIRSG/xnat-aws#102]
### Short Description

When trying to run a container using the current deployment setup, it fails

### Evidence/Steps to Reproduce

Follow the README.md document, including:
* `terraform apply`
* In ./configure, run `./install_xnat.sh`
* Then run `./setup_xnat.sh`
* Run the dmc2niix container as part of the instructions in the [MEDICSS tutorial](https://healthbioscienceideas.github.io/MedICSS-Project-Repro-Pipelines/)

### Acceptance Criteria/Expected Behaviour

The system should be able to run the containers automatically without the user having to go in and manually downgrade the DOcker. 

### Details

[This thread](https://groups.google.com/g/xnat_discussion/c/yyPBkN4kayE/m/8Lv_ppCFAAAJ) and [this one](https://groups.google.com/g/xnat_discussion/c/rhGI_Yuho_s) seems to suggest it is a problem with DOcker above version 24. I confirmed this by running `sudo yum downgrade docker-ce-3:24.0.9-1.el9.x86_64` on the container server and the containers run fine after the downgrade.

**Comment by p-j-smith** [comment]
This is fixed in the latest version of our Ansible setup, and I'm planning to open a PR soon to switch to that (sorry if it wasted your time troubleshooting this!)
