### ISSUE TITLE
Update cost estimate

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/xnat-aws#114]
### Short Description

It would be good to update the [cost estimate](https://github.com/UCL-MIRSG/xnat-aws?tab=readme-ov-file#aws-cost-estimate) based on actual running costs

@davecash75 or @HChughtai do you know how much it cost to run the workshop last week?

**Comment by HChughtai** [comment]
I'm trying to interpret the cost dashboard on the IDEAS AWS portal, but I think the cost for what was deployed was around $6 a day, so $3 per instance. But I'm struggling to figure out exactly what was due to what we deployed for this project and what is other stuff that's running.

**Comment by davecash75** [comment]
I think this is one of the things tags are good for, which I thought terraform did do, but I can't find it on the Cost Explorer for some reason. Maybe we have to tag it with the right label.
July: Total costs of $74.54, minus Appstream costs of 14.17 for another project, which also incurred some of the EFS costs. The rest is for EC2, RDS, VPC, etc. So as Haroon says roughly $6-7 a day (60/9) for everything
We had some development time in June, I'd say about $60-80 from the bills, but I wouldn't put that on the cost estimate.

**Comment by HChughtai** [comment]
I did tag the resources when I brought them up, but couldn't find it either. I wonder if once the resources are brought down the tags are removed?

**Comment by p-j-smith** [comment]
Thanks both for checking. 

> July: Total costs of $74.54, minus Appstream costs of 14.17 for another project, which also incurred some of the EFS costs. The rest is for EC2, RDS, VPC, etc. So as Haroon says roughly $6-7 a day (60/9) for everything
We had some development time in June, I'd say about $60-80 from the bills, but I wouldn't put that on the cost estimate.

Okay, seeing as it seems to have cost less than the current estimate, and we don't know for sure how much it cost, let just leave the current estimate. At least that way no one should get a nasty surprise
