### ISSUE TITLE
Remove database subnet

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/xnat-aws#62]
I think we don't need both the private and database subnets - the database subnet [can be used to expose the database to the public](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/5.0.0#public-access-to-rds-instances:~:text=%23%20...%20omitted%0A%7D-,Public%20access%20to%20RDS%20instances,-Sometimes%20it%20is), but is not recommended.

We could [create our own `aws_db_subnet_group`](https://developer.hashicorp.com/terraform/tutorials/aws/aws-rds#subnet-group) (using the private subnets), and use this when creating the RDS instance

**Comment by milanmlft** [comment]
I agree we don't need them. The only reason I added them is because the `setup_vpc` module failed when only enabling `database_subnets` without any private subnets. See https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/944.
