### ISSUE TITLE
Make sure EFS is being used for file storage

### ISSUE THREAD

**Issue by milanmlft** [UCL-MIRSG/xnat-aws#69]
#67 seems to indicate that the EFS is not properly used. We would expect the file system to increase in size as needed so we should not run into problems due to insufficient storage space.

**Comment by p-j-smith** [comment]
I just tried manually pulling the `healthbioscienceideas/fastsurfer:gpu` image on the Container Service server and had the same error:

```
[rocky@ip-192-168-56-14 ~]$ sudo docker pull healthbioscienceideas/fastsurfer:gpu
gpu: Pulling from healthbioscienceideas/fastsurfer
80bce60046fa: Pull complete
55a738a15540: Pull complete
e19cf0706c62: Pull complete
de4cdd6c27d1: Pull complete
ec1a9bd0eb8c: Pull complete
8a6a57c93768: Pull complete
ff5439271f3c: Pull complete
5ee84dae1e02: Pull complete
647c4b3e1fdb: Pull complete
9c39f3ebb735: Pull complete
26eda9e73d5b: Pull complete
a6e0b974516e: Extracting  2.765GB/2.765GB
d87a14d7e28a: Download complete
e86eb8ebd148: Download complete
failed to register layer: write /opt/freesurfer/bin/dmri_forrest: no space left on device
```

So the issue isn't with the XNAT data, but with the size of the docker images we're using. Either we could symlink `/var/lib/docker/overlay2` (where images are stored) to somewhere on the EFS, or just keep the larger root block device on the Container Service server?

**Comment by milanmlft** [comment]
Yeah, putting the images on EFS might be more future proof, if at some point we would ever need even more space.
