### ISSUE TITLE
`pydeface` missing when converting NIFTI to 256 conformed MGZ file

### ISSUE THREAD

**Issue by milanmlft** [UCL-MIRSG/xnat-aws#70]
When running the `Converts NIFTI to 256 conformed MGZ file` command, as part of the IDEAS workshop (see #44), we run into the following error:

```
/fastsurfer/nii_to_mgz.sh: line 27: pydeface: command not found
Deface failed
```

What is confusing is that in the workshop, the defacing is performed _after_ the first run of FastSurfer (after which FastSurfer is re-run to see the impact on the results). So there is no need to have `pydeface` when we just want to convert the NIFTI files to MGZ, I think?

**Comment by milanmlft** [comment]
https://github.com/UCL-MIRSG/xnat-aws/issues/51#issuecomment-1679132158 suggests changing the image for the `pydeface` command. However, running the `Defaces a T1 Nifti scan` command on a NIFTI-converted scan works fine when using the `healthbioscienceideas/pydeface:minify` image.

So the problem seems to be a missing `pydeface` installation in the `fastsurfer` container (used for the MGZ conversion).

**Comment by p-j-smith** [comment]
> https://github.com/UCL-MIRSG/xnat-aws/issues/51#issuecomment-1679132158 suggests changing the image for the pydeface command. However, running the Defaces a T1 Nifti scan command on a NIFTI-converted scan works fine when using the healthbioscienceideas/pydeface:minify image.
>
>So the problem seems to be a missing pydeface installation in the fastsurfer container (used for the MGZ conversio

ah good point!

**Comment by milanmlft** [comment]
Not sure if there is anything we can do about this? Seems more like a problem on the XNAT side, not with our AWS setup?

**Comment by milanmlft** [comment]
I had a look into the `healthbioscienceideas/fastsurfer:gpu` Docker container, and there the `nii_to_mgz.sh` actually looks like this:

```sh
#!/usr/bin/env bash
# Wrapper script around pydeface, so that it can yank the first
# probably only file from the inoput directory
# and preserve all other arguments

die(){
    echo >&2 "$@"
    exit 1
}

IN_DIR=$1
shift
OUT_DIR=$1
shift

IN_FILE=$(ls ${IN_DIR}/*.nii* | head -1)
[[ -f ${IN_FILE} ]] || die "Did not find nii or nii.gz file in ${IN_DIR}"
IN_BASE=`basename ${IN_FILE} .gz`
IN_BASE=`basename ${IN_BASE} .nii`
OUT_FILE=${OUT_DIR}/${IN_BASE}.mgz

export PATH=/opt/miniconda-latest/envs/neuro/bin:${PATH}
echo IN_FILE=${IN_FILE}
echo OUT_FILE=${OUT_FILE}
echo
echo mri_convert $@ ${IN_FILE} ${OUT_FILE}
pydeface $@ ${IN_FILE} ${OUT_FILE} || die "Deface failed"
```

So it does indeed call `pydeface` in the last line and is different from the script mentioned above. Not sure whether this is an error or not?

**Comment by HChughtai** [comment]
That's an error and I think that Docker image is out of date, and so has the wrong version. You can see in https://github.com/HealthBioscienceIDEAS/MedICSS-Project-Repro-Pipelines/blob/gh-pages/fastsurfer/nii_to_mgz.sh that the line doesn't exist.

And you're right that it should be a separate step to the conversion. I think what happened was that Dave created nii_to_mgz.sh by copying run_pydeface.sh and that was left behind. I'd suggest rebuilding the fastsurfer image

**Comment by milanmlft** [comment]
Thanks @HChughtai! Can confirm that manually editing the `nii_to_mgz.sh` script in the Docker container on AWS and just replacing `pydeface` with `mri_convert` in that last line gets rid of the error. But now I'm getting this:

```
--------------------------------------------------------------------------
ERROR: FreeSurfer license file /fs60/license.txt not found.
  If you are outside the NMR-Martinos Center,
  go to http://surfer.nmr.mgh.harvard.edu/registration.html to 
  get a valid license file (it's free).
  If you are inside the NMR-Martinos Center,
  make sure to source the standard environment.
  A path to an alternative license file can also be
  specified with the FS_LICENSE environmental variable.
--------------------------------------------------------------------------
Deface failed
```

Do we just need to create a new license and add it to the Docker container?

**Comment by HChughtai** [comment]
> Do we just need to create a new license and add it to the Docker container?

Yeah, that would do it !
